version: "3.9"

services:

  notification-item-1:
    image: fort163/qr-notification-service:0.0.1-SNAPSHOT
    environment:
      - ACTIVE_PROFILE=${PROFILE}
      - CONFIG_SERVER=${CONFIG_SERVER}
      - INSTANCE_HOSTNAME=notification-cluster-notification-item-1-1
    ports:
      - "8050:8050"
    networks:
      - notification-infrastructure
      - kafka
      - single-service

  notification-item-2:
    image: fort163/qr-notification-service:0.0.1-SNAPSHOT
    environment:
      - ACTIVE_PROFILE=${PROFILE}
      - CONFIG_SERVER=${CONFIG_SERVER}
      - SERVER_PORT=8051
      - INSTANCE_HOSTNAME=notification-cluster-notification-item-2-1
    ports:
      - "8051:8051"
    networks:
      - notification-infrastructure
      - kafka
      - single-service

networks:
  single-service:
    external: true
    name: single-service-network
  notification-infrastructure:
    external: true
    name: notification-infrastructure-network
  kafka:
    external: true
    name: kafka-network